# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNegativeLogin():
def setup_method(self, method):
self.driver = webdriver.Chrome()
self.vars = {}

def teardown_method(self, method):
self.driver.quit()

def test_negativeLogin(self):
# Test name: Negative Login
# Step # | name | target | value
# 1 | open | /v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&hl=id&ifkv=ASKXGp2mneQBGJ5CgW2Q7dS0X6ZFDykvP85x4FbNqre4G_st_23snlSfepSPNWSOo3mviMF6Iu9Z8A&rip=1&sacu=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S1258709686%3A1706636902578712&theme=glif |
self.driver.get("https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&hl=id&ifkv=ASKXGp2mneQBGJ5CgW2Q7dS0X6ZFDykvP85x4FbNqre4G_st_23snlSfepSPNWSOo3mviMF6Iu9Z8A&rip=1&sacu=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S1258709686%3A1706636902578712&theme=glif")
# 2 | setWindowSize | 562x454 |
self.driver.set_window_size(562, 454)
# 3 | click | id=identifierId |
self.driver.find_element(By.ID, "identifierId").click()
# 4 | type | id=identifierId | test@gmail.com
self.driver.find_element(By.ID, "identifierId").send_keys("test@gmail.com")
# 5 | click | css=.VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d |
self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d").click()
# 6 | mouseOver | css=.VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d |
element = self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")
actions = ActionChains(self.driver)
actions.move_to_element(element).perform()
# 7 | mouseOut | css=.VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d |
element = self.driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(self.driver)
actions.move_to_element(element, 0, 0).perform()
# 8 | click | id=headingSubtext |
self.driver.find_element(By.ID, "headingSubtext").click()
# 9 | verifyText | css=#headingSubtext > span | Gunakan Akun Google Anda
assert self.driver.find_element(By.CSS_SELECTOR, "#headingSubtext > span").text == "Gunakan Akun Google Anda"
# 10 | close |  |
self.driver.close()
