# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPositivelogin():
def setup_method(self, method):
self.driver = webdriver.Chrome()
self.vars = {}

def teardown_method(self, method):
self.driver.quit()

def test_positivelogin(self):
# Test name: positive login
# Step # | name | target | value
# 1 | open | /v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F%3Ftab%3Drm%26ogbl&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F%3Ftab%3Drm%26ogbl&ifkv=ASKXGp1Ct4ND29xbgEy_mtOAsjG1YlTMFcQKg1-zYDZQZNV4E7_wZ-zShr7YvK7MQrheZhdPUAEU&osid=1&passive=1209600&service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-1442749726%3A1706635549000828&theme=glif |
self.driver.get("https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F%3Ftab%3Drm%26ogbl&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F%3Ftab%3Drm%26ogbl&ifkv=ASKXGp1Ct4ND29xbgEy_mtOAsjG1YlTMFcQKg1-zYDZQZNV4E7_wZ-zShr7YvK7MQrheZhdPUAEU&osid=1&passive=1209600&service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-1442749726%3A1706635549000828&theme=glif")
# 2 | setWindowSize | 526x454 |
self.driver.set_window_size(526, 454)
# 3 | runScript | window.scrollTo(0,0) |
self.driver.execute_script("window.scrollTo(0,0)")
# 4 | click | css=.aAD |
self.driver.find_element(By.CSS_SELECTOR, ".aAD").click()
# 5 | assertText | id=:1r | Belum Dibaca
assert self.driver.find_element(By.ID, ":1r").text == "Belum Dibaca"
# 6 | verifyText | id=:1r | Belum Dibaca
assert self.driver.find_element(By.ID, ":1r").text == "Belum Dibaca"
# 7 | close |  |
self.driver.close()
